version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"  # Map host port 8000 to container port 9000
    volumes:
      - .:/var/www/html  # Mount the current directory to container's working directory
