version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
networks:
  default:
   name: arcson
   external: true